// STATUS CODE
const HTTP_STATUS_OK = 200;
const HTTP_INTERNAL_SERVER_ERROR = 500;
const HTTP_CREATED = 201;
const HTTP_NOT_CONTENT = 204;
const HTTP_NOT_FOUND = 404;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;

const ROLE_USER = 'ROLE_USER';

const MSG_ERROR_ADMINISTRADOR = 'Error inesperado... Consultar con el Administrador';
const EXTENSIONES_VALIDAS = ['png', 'jpg', 'jpeg', 'gif'];

// Tamaño de fotos de perfil 180px x 180px
const SIZE_PERFIL_PHOTO = [180, 180];

module.exports = {
    HTTP_STATUS_OK,
    HTTP_CREATED,
    HTTP_NOT_CONTENT,
    HTTP_BAD_REQUEST,
    HTTP_UNAUTHORIZED,
    HTTP_NOT_FOUND,
    HTTP_INTERNAL_SERVER_ERROR,
    ROLE_USER,
    MSG_ERROR_ADMINISTRADOR,
    EXTENSIONES_VALIDAS,
    SIZE_PERFIL_PHOTO
}